from enum import Enum


class Constants(float, Enum):
    CLICK_GAP_THRESHOLD = 0.2
    MOVE_GAP_THRESHOLD = 0.5
    SCROLL_GAP_THRESHOLD = 0.5
    KEY_GAP_THRESHOLD = 0.5
    CLICK_TOTAL_THRESHOLD = 0.3
    MOVE_TOTAL_THRESHOLD = 4.0
    SCROLL_TOTAL_THRESHOLD = 3.0
    KEY_TOTAL_THRESHOLD = 6.0
    PADDING_BEFORE = 75
    PADDING_AFTER = 75
    FINAL_PADDING = 100


MAX_TOTAL_THRESHOLD = max(
    Constants.CLICK_TOTAL_THRESHOLD,
    Constants.MOVE_TOTAL_THRESHOLD,
    Constants.SCROLL_TOTAL_THRESHOLD,
    Constants.KEY_TOTAL_THRESHOLD
)
